import "./globals.css"
import type { Metadata } from "next"
import clsx from "clsx"
import { Inter } from "next/font/google"
import { ApolloProvider, LocalizationProvider, ThemeProvider } from "providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={clsx(inter.className, "h-screen w-screen")}>
        <ThemeProvider>
          <LocalizationProvider>
            <ApolloProvider>{children}</ApolloProvider>
          </LocalizationProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
